config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "articles#index"
  resources :articles do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
  post   '/like/:id' => 'likes#create',   as: 'create_like'
  delete '/like/:id' => 'likes#destroy',  as: 'destroy_like'
end

app/models/article.rb
class Article < ApplicationRecord
  with_options presence: true do
    validates :name, length: { maximum: 40 }
    with_options numericality: { other_than: 1 } do
      validates :prefecture_id
      validates :bath_type_id
      validates :temperature_id
      validates :breadth_id
      validates :water_bath_id
      validates :break_space_id
      validates :budget_id
      validates :number_of_visit_id
      validates :evaluation_id
    end
    validates :general_comment, length: { maximum: 1000 }
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :bath_type
  belongs_to :temperature
  belongs_to :breadth
  belongs_to :water_bath
  belongs_to :break_space
  belongs_to :budget
  belongs_to :number_of_visit
  belongs_to :evaluation

  def self.search(search)
    if search != ""
      Article.where('name LIKE(?)', "%#{search}%")
    else
      Article.all
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :contributor_confirmation, only: [:edit, :update, :destroy]

  def index
    @articles = Article.order("created_at DESC").includes(:user)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to root_path(anchor: 'articles-lists')
    else
      render :new
    end
  end

  def show
    @comment = Comment.new
    @comments = @article.comments.order("created_at DESC").includes(:user)
  end

  def edit
  end

  def update
    if @article.update(article_params)
      redirect_to article_path
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to root_path
  end

  def search
    @articles = Article.search(params[:keyword])
  end

  private

  def article_params
    params.require(:article).permit(:image, :name, :prefecture_id, :bath_type_id, :temperature_id, :breadth_id, :water_bath_id, :break_space_id,
                                    :budget_id, :number_of_visit_id, :evaluation_id, :general_comment).merge(user_id: current_user.id)
  end

  def set_article
    @article = Article.find(params[:id])
  end

  def contributor_confirmation
    redirect_to action: :index unless current_user == @article.user
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/edit.html.erb
<%# cssは記事投稿のものを併用しています。
app/assets/stylesheets/items/new.css %>

<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('sauna.png' , size: '185x100'), "/" %>
  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">サウナの情報を入力</h2>
    <%= form_with(model: @article, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        サウナ画像
        <span class="indispensable2">任意</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
        <div class="image-list" id="image-list"></div>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        サウナ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"サウナの名称（40文字まで)", maxlength:"40" %>
      <div class="items-explain">
        <div class="weight-bold-text">
          所在地
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"article-prefecture"}) %>
      </div>
    </div>

    <%# サウナの詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">サウナの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          風呂の種類
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:bath_type_id, BathType.all, :id, :name, {}, {class:"select-box", id:"article-gender-bath"}) %>
        <div class="weight-bold-text">
          サウナの温度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:temperature_id, Temperature.all, :id, :name, {}, {class:"select-box", id:"article-heat"}) %>
        <div class="weight-bold-text">
          サウナの広さ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:breadth_id, Breadth.all, :id, :name, {}, {class:"select-box", id:"article-breadth"}) %>
        <div class="weight-bold-text">
          水風呂の温度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:water_bath_id, WaterBath.all, :id, :name, {}, {class:"select-box", id:"article-water-temperature"}) %>
        <div class="weight-bold-text">
          休憩スペース
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:break_space_id, BreakSpace.all, :id, :name, {}, {class:"select-box", id:"article-lounge"}) %>
        <div class="weight-bold-text">
          予算
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:budget_id, Budget.all, :id, :name, {}, {class:"select-box", id:"article-budget"}) %>
        <div class="weight-bold-text">
          来店回数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:number_of_visit_id, NumberOfVisit.all, :id, :name, {}, {class:"select-box", id:"article-visit"}) %>
        <div class="weight-bold-text">
          総合評価
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"article-evaluation"}) %>
      </div>
    </div>

    <div class="new-items">
      <div class="items-explain">
        <div class="weight-bold-text">
          サウナの総評
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :general_comment, class:"items-text", id:"article-impressions", placeholder:"全体的な感想（1,000文字まで入力可）（温度、規模、雰囲気など何でも記入OK!!）例）サウナの温度、湿度が絶妙で居心地が最高によかったです。時計が故障中だったので時間を計れなかったことが少し残念でした。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "変更する" ,class:"sell-btn" %>
      <%=link_to 'もどる', article_path(@article.id), class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#"></a></li>
      <li><a href="#"></a></li>
      <li><a href="#"></a></li>
    </ul>
    <%= link_to image_tag('sauna.png' , size: '185x100'), "/" %>
    <p class="inc">
      ©︎GetReadyサウナ!!,Inc.
    </p>
  </footer>
</div>

app/views/articles/index.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <h1 class='service-title'>
      Get Ready サウナ!!
    </h1>
    <p class='service-explain'>
      おすすめのサウナを投稿しよう!
    </p>
    <p class='service-explain'>
      整える(Get Ready)サウナを見つけ出せ！
    </p>
  </div>

  

  <div class='ad-contents'>
    <h2 class='ad-title'>
      サウナのあとの至福の水風呂
    </h2>
    <p class='ad-explain'>
      整える場所には至極の水風呂あり
    </p>
    <p class='ad-explain'>
      サウナと水風呂は一心同体です
    </p>
  </div>

  <div class='feature-contents'>
    <h2 class='title'>
      ✨整う流れ✨
    </h2>
    <ul class='feature-lists'>
      <li class='list'>
        <%= image_tag "sauna3.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          サウナに入る
        </h3>
        <p class='feature-list-description'>
          6~12分程度入り、体全体を熱します。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "mizuburo3.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          水風呂に浸かる
        </h3>
        <p class='feature-list-description'>
          1~2分程度浸かり、熱せられた体を冷やします。
        </p>
      </li>
      <li class='list'>
        <%= image_tag "gaikiyoku.png", class:"list-pict" %>
        <h3 class='feature-list-text'>
          休憩し、整う
        </h3>
        <p class='feature-list-description'>
          体の水分を拭き取ったあと、ベンチに座り整います。
        </p>
      </li>
    </ul>
  </div>

  <div class='item-contents', id='articles-lists'>
    <h2 class='title'>♨️サウナ記事一覧♨️</h2>
    <ul class='item-lists'>

    <% @articles.each do |article| %>
      <li class='list'>
        <%= link_to article_path(article.id) do %>
        <div class='item-img-content'>
        <% if article.image.attached? %>
          <%= image_tag article.image, class: "item-img" %>
        <% else %>
          <%= image_tag "unnamed.png", class: "item-img" %>
        <% end %>
        </div>
        <div class='item-info'>
          <h3 class='item-name'>
            <%= article.name %>
          </h3>
          <div class='item-place'>
            <span><%= article.prefecture.name %><br><%= article.budget.name %></span>
            <div class='star-btn'>
              <%= image_tag "star.png", class:"star-icon" %>
              <span class='star-count'><%= article.evaluation.name %></span>
            </div>
          </div>
        </div>
        <% end %>
      </li>
    <% end %>

      <% if @articles.length == 0 %>
        <li class='list'>
          <%= link_to '#' do %>
          <%= image_tag "sauna1.jpg", class: "item-img" %>
          <div class='item-info'>
            <h3 class='item-name'>
              おすすめのサウナを投稿してね！
            </h3>
            <div class='item-price'>
              <span>都道府県<br>予算</span>
              <div class='star-btn'>
                <%= image_tag "star.png", class:"star-icon" %>
                <span class='star-count'>評価</span>
              </div>
            </div>
          </div>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
  <%# /投稿一覧 %>
</div>
<%= link_to(new_article_path, class: 'purchase-btn') do %>
  <span class='purchase-btn-text'>投稿する</span>
  <%= image_tag 'sauna_logo.jpg' , size: '185x50' ,class: "purchase-btn-icon" %>
<% end %>
<%= render "shared/footer" %>

app/views/articles/new.html.erb
<div class="items-sell-contents">
  <header class="items-sell-header">
    <%= link_to image_tag('sauna.png' , size: '185x100'), "/" %>

  </header>
  <div class="items-sell-main">
    <h2 class="items-sell-title">サウナの情報を入力</h2>
    <%= form_with(model: @article, local: true) do |f| %>

    <%= render 'shared/error_messages', model: f.object %>

    <div class="img-upload">
      <div class="weight-bold-text">
        サウナ画像
        <span class="indispensable2">任意</span>
      </div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
        <div class="image-list" id="image-list"></div>
      </div>
    </div>

    <div class="new-items">
      <div class="weight-bold-text">
        サウナ名
        <span class="indispensable">必須</span>
      </div>
      <%= f.text_area :name, class:"items-text", id:"item-name", placeholder:"サウナの名称（40文字まで)", maxlength:"40" %>
    </div>

    <%# サウナの詳細 %>
    <div class="items-detail">
      <div class="weight-bold-text">サウナの詳細</div>
      <div class="form">
        <div class="weight-bold-text">
          所在地
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"article-prefecture"}) %>
        <div class="weight-bold-text">
          風呂の種類
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:bath_type_id, BathType.all, :id, :name, {}, {class:"select-box", id:"article-gender-bath"}) %>
        <div class="weight-bold-text">
          サウナの温度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:temperature_id, Temperature.all, :id, :name, {}, {class:"select-box", id:"article-heat"}) %>
        <div class="weight-bold-text">
          サウナの広さ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:breadth_id, Breadth.all, :id, :name, {}, {class:"select-box", id:"article-breadth"}) %>
        <div class="weight-bold-text">
          水風呂の温度
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:water_bath_id, WaterBath.all, :id, :name, {}, {class:"select-box", id:"article-water-temperature"}) %>
        <div class="weight-bold-text">
          休憩スペース
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:break_space_id, BreakSpace.all, :id, :name, {}, {class:"select-box", id:"article-lounge"}) %>
        <div class="weight-bold-text">
          予算
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:budget_id, Budget.all, :id, :name, {}, {class:"select-box", id:"article-budget"}) %>
        <div class="weight-bold-text">
          来店回数
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:number_of_visit_id, NumberOfVisit.all, :id, :name, {}, {class:"select-box", id:"article-visit"}) %>
        <div class="weight-bold-text">
          総合評価
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:evaluation_id, Evaluation.all, :id, :name, {}, {class:"select-box", id:"article-evaluation"}) %>
      </div>
    </div>

    <div class="new-items">
      <div class="items-explain">
        <div class="weight-bold-text">
          サウナの総評
          <span class="indispensable">必須</span>
        </div>
        <%= f.text_area :general_comment, class:"items-text", id:"article-impressions", placeholder:"全体的な感想（1,000文字まで入力可）（温度、規模、雰囲気など何でも記入OK!!）例）サウナの温度、湿度が絶妙で居心地が最高によかったです。時計が故障中だったので時間を計れなかったことが少し残念でした。" ,rows:"7" ,maxlength:"1000" %>
      </div>
    </div>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class:"sell-btn" %>
      <%=link_to 'もどる', root_path, class:"back-btn" %>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>

  <footer class="items-sell-footer">
    <ul class="menu">
      <li><a href="#"></a></li>
      <li><a href="#"></a></li>
      <li><a href="#"></a></li>
    </ul>
    <%= link_to image_tag('sauna.png' , size: '185x100'), "/" %>
    <p class="inc">
      ©︎GetReadyサウナ!!,Inc.
    </p>
  </footer>
</div>

app/views/articles/search.html.erb
<%= render "shared/header" %>

<ul class='item-lists'>
  <% @articles.each do |article| %>
    <li class='list'>
      <%= link_to article_path(article.id) do %>
      <div class='item-img-content'>
      <% if article.image.attached? %>
        <%= image_tag article.image, class: "item-img" %>
      <% else %>
        <%= image_tag "unnamed.png", class: "item-img" %>
      <% end %>
      </div>
      <div class='item-info'>
        <h3 class='item-name'>
          <%= article.name %>
        </h3>
        <div class='item-price'>
          <span><%= article.prefecture.name %><br><%= article.budget.name %></span>
          <div class='star-btn'>
            <%= image_tag "star.png", class:"star-icon" %>
            <span class='star-count'><%= article.evaluation.name %></span>
          </div>
        </div>
      </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<%= render "shared/header" %>

<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @article.name %>
    </h2>
    <div class="item-img-content">
      <% if @article.image.attached? %>
          <%= image_tag @article.image, class: "item-img" %>
        <% else %>
          <%= image_tag "unnamed.png", class: "item-img" %>
        <% end %>
    </div>
    <div class="item-price-box">
      <span class="item-price">
        <%= @article.budget.name %>
      </span>
      <span class="item-postage">
        <%= @article.prefecture.name %>
      </span>
    </div>

    <% if user_signed_in? %>
      <% if current_user.id == @article.user_id %>
        <%= link_to "投稿記事の編集", edit_article_path(@article.id), method: :get, class: "item-red-btn" %>
        <p class="or-text">or</p>
        <%= link_to "投稿記事の削除", article_path(anchor: 'articles-lists'), method: :delete, class:"item-destroy" %>
      <% end %>
    <% end %>

    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">投稿者</th>
          <td class="detail-value"><%= link_to @article.user.nickname, user_path(@article.user_id), class: "detail-name" %></td>
        </tr>
        <tr>
          <th class="detail-item">風呂の種類</th>
          <td class="detail-value"><%= @article.bath_type.name %></td>
        </tr>
        <tr>
          <th class="detail-item">サウナの温度</th>
          <td class="detail-value"><%= @article.temperature.name %></td>
        </tr>
        <tr>
          <th class="detail-item">サウナの広さ</th>
          <td class="detail-value"><%= @article.breadth.name %></td>
        </tr>
        <tr>
          <th class="detail-item">水風呂の温度</th>
          <td class="detail-value"><%= @article.water_bath.name %></td>
        </tr>
        <tr>
          <th class="detail-item">休憩スペース</th>
          <td class="detail-value"><%= @article.break_space.name %></td>
        </tr>
        <tr>
          <th class="detail-item">来店回数</th>
          <td class="detail-value"><%= @article.number_of_visit.name %></td>
        </tr>
        <tr>
          <th class="detail-item">評価</th>
          <td class="detail-value"><%= @article.evaluation.name %></td>
        </tr>
      </tbody>
    </table>

    <div class="item-explain-comment">
      <%= @article.general_comment %>
    </div>
    <div class="like-link" id="like-link-<%= @article.id %>">
      <%= render partial: 'likes/like', locals: { article: @article } %>
    </div>
  </div>

  <div class="comment-box">
    <% if user_signed_in? %>
      <%= form_with(model: [@article, @comment], local: true) do |f| %>
        <%= f.text_area :text, class: "comment-text" %>
        <p class="comment-warn">
          相手のことを考え丁寧なコメントを心がけましょう。
          <br>
          不快な言葉遣いなどは利用制限や退会処分となることがあります。
        </p>
        <button type="submit" class="comment-btn">
          <%= image_tag "comment.png" ,class:"comment-flag-icon" ,width:"20",height:"25"%>
          <span>コメントする<span>
        </button>
      <% end %>
    <% end %>
  </div>
    
  <div class="change-item-btn">
    💬コメント一覧💬
  </div>
    <ul class="comments_lists">
      <% @comments.each do |comment| %>
        <li class="comments_list">
            <p>
              <%= link_to "#{comment.user.nickname} :", user_path(comment.user_id), class: "comment-up" %>
                <%= comment.text %>
                <% if current_user == comment.user %>
                  <%= link_to "削除", article_comment_path(@article, comment), method: :delete, class: "comment-up" %>
                <% end %>
            </p>
        </li>
      <% end %>
    </ul>
  <div class="links">
    <%= link_to "＜ 前の投稿📝", article_path(@article.id), class: "change-article-btn" %>
    <%= link_to "後ろの投稿📝 ＞", article_path(@article.id), class: "change-article-btn" %>
    </a>
  </div>
  <%= link_to "#{@article.user.nickname}さんの投稿をもっと見る", user_path(@article.user_id, anchor: 'user-articles'), class: "another-item" %>
</div>

<%= render "shared/footer" %>