config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "articles#index"
  resources :articles do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
  post   '/like/:id' => 'likes#create',   as: 'create_like'
  delete '/like/:id' => 'likes#destroy',  as: 'destroy_like'
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  def self.get_likes_articles(user)
    where(user_id: user.id).map(&:article)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :set_variables, only: [:create, :destroy]
  before_action :authenticate_user!

  def create
    Like.create(user_id: current_user.id, article_id: params[:id])
  end

  def destroy
    Like.find_by(user_id: current_user.id, article_id: params[:id]).destroy
  end

  private 

  def set_variables
    @article = Article.find(params[:id])
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like.html.erb
<% if user_signed_in? %>
  <% if current_user.likes.find_by(article_id: @article.id) %>
    <%= link_to destroy_like_path(@article.id), method: :delete, remote: true do %>
        <div class = "iine__button">❤️<%= @article.likes.count %></div>
    <% end %>
  <% else %>
    <%= link_to create_like_path(@article.id), method: :post, remote: true do %>
        <div class = "iine__button">♡️<%= @article.likes.count %></div>
    <% end %>
  <% end %>
<% end %>

app/views/likes/create.js.erb
$('#like-link-<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: { article: @article }) %>");

app/views/likes/destroy.js.erb
$('#like-link-<%= @article.id %>').html("<%= j(render partial: 'likes/like', locals: { article: @article }) %>");