config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root to: "articles#index"
  resources :articles do
    resources :comments, only: [:create, :destroy]
    collection do
      get 'search'
    end
  end
  resources :users, only: [:show, :edit, :update]
  post   '/like/:id' => 'likes#create',   as: 'create_like'
  delete '/like/:id' => 'likes#destroy',  as: 'destroy_like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  with_options presence: true do
    validates :name, length: { maximum: 40 }
    with_options numericality: { other_than: 1 } do
      validates :prefecture_id
      validates :bath_type_id
      validates :temperature_id
      validates :breadth_id
      validates :water_bath_id
      validates :break_space_id
      validates :budget_id
      validates :number_of_visit_id
      validates :evaluation_id
    end
    validates :general_comment, length: { maximum: 1000 }
  end

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :prefecture
  belongs_to :bath_type
  belongs_to :temperature
  belongs_to :breadth
  belongs_to :water_bath
  belongs_to :break_space
  belongs_to :budget
  belongs_to :number_of_visit
  belongs_to :evaluation

  def self.search(search)
    if search != ""
      Article.where('name LIKE(?)', "%#{search}%")
    else
      Article.all
    end
  end
end

app/models/bath_type.rb
class BathType < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男湯(漢のサウナ)' },
    { id: 3, name: '女湯(乙女のサウナ)' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/breadth.rb
class Breadth < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '狭い' },
    { id: 3, name: 'やや狭い' },
    { id: 4, name: '普通' },
    { id: 5, name: '広め' },
    { id: 6, name: 'かなり広め' },
    { id: 7, name: '大広間' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/break_space.rb
class BreakSpace < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '狭め 外気浴なし' },
    { id: 3, name: '普通 外気浴なし' },
    { id: 4, name: '広い 外気浴なし' },
    { id: 5, name: '狭め 外気浴あり' },
    { id: 6, name: '普通 外気浴あり' },
    { id: 7, name: '広い 外気浴あり' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/budget.rb
class Budget < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '¥1,000円未満' },
    { id: 3, name: '¥1,000円〜¥2,000円' },
    { id: 4, name: '¥2,000円〜¥3,000円' },
    { id: 5, name: '¥3,000円〜¥4,000円' },
    { id: 6, name: '¥4,000円〜¥5,000円' },
    { id: 7, name: '¥5,000円〜' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :text, presence: true, length: { maximum: 1000 }

  belongs_to :user
  belongs_to :article
end

app/models/evaluation.rb
class Evaluation < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '冥界(地獄の入り口)' },
    { id: 3, name: '微妙(少し物足りない)' },
    { id: 4, name: '無難(悪くはない)' },
    { id: 5, name: '普通(ちょうど良い)' },
    { id: 6, name: '実家(マイホーム)' },
    { id: 7, name: '楽園(整い絶頂)' },
    { id: 8, name: '天国(天に召される)' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/gender.rb
class Gender < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '男性(サ活男子)' },
    { id: 3, name: '女性(サ活女子)' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :article

  def self.get_likes_articles(user)
    where(user_id: user.id).map(&:article)
  end
end

app/models/number_of_visit.rb
class NumberOfVisit < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '初めて' },
    { id: 3, name: '2回〜3回目' },
    { id: 4, name: '3回〜5回目' },
    { id: 5, name: '5回〜10回目' },
    { id: 6, name: '10回以上' },
    { id: 7, name: '毎日' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/prefecture.rb
class Prefecture < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '北海道' },
    { id: 3, name: '青森県' },
    { id: 4, name: '岩手県' },
    { id: 5, name: '宮城県' },
    { id: 6, name: '秋田県' },
    { id: 7, name: '山形県' },
    { id: 8, name: '福島県' },
    { id: 9, name: '茨城県' },
    { id: 10, name: '栃木県' },
    { id: 11, name: '群馬県' },
    { id: 12, name: '埼玉県' },
    { id: 13, name: '千葉県' },
    { id: 14, name: '東京都' },
    { id: 15, name: '神奈川県' },
    { id: 16, name: '新潟県' },
    { id: 17, name: '富山県' },
    { id: 18, name: '石川県' },
    { id: 19, name: '福井県' },
    { id: 20, name: '山梨県' },
    { id: 21, name: '長野県' },
    { id: 22, name: '岐阜県' },
    { id: 23, name: '静岡県' },
    { id: 24, name: '愛知県' },
    { id: 25, name: '三重県' },
    { id: 26, name: '滋賀県' },
    { id: 27, name: '京都府' },
    { id: 28, name: '大阪府' },
    { id: 29, name: '兵庫県' },
    { id: 30, name: '奈良県' },
    { id: 31, name: '和歌山県' },
    { id: 32, name: '鳥取県' },
    { id: 33, name: '島根県' },
    { id: 34, name: '岡山県' },
    { id: 35, name: '広島県' },
    { id: 36, name: '山口県' },
    { id: 37, name: '徳島県' },
    { id: 38, name: '香川県' },
    { id: 39, name: '愛媛県' },
    { id: 40, name: '高知県' },
    { id: 41, name: '福岡県' },
    { id: 42, name: '佐賀県' },
    { id: 43, name: '長崎県' },
    { id: 44, name: '熊本県' },
    { id: 45, name: '大分県' },
    { id: 46, name: '宮崎県' },
    { id: 47, name: '鹿児島県' },
    { id: 48, name: '沖縄県' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/sauna_history.rb
class SaunaHistory < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'サウナ初級者' },
    { id: 3, name: 'サウナ駆け出し' },
    { id: 4, name: 'サウナ中級者' },
    { id: 5, name: 'サウナ熟練者' },
    { id: 6, name: 'サウナ上級者' },
    { id: 7, name: 'サウナ魔神' }
  ]

  include ActiveHash::Associations
  has_many :users
end

app/models/temperature.rb
class Temperature < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: '低い' },
    { id: 3, name: 'やや低め' },
    { id: 4, name: '普通' },
    { id: 5, name: 'やや高め' },
    { id: 6, name: '高い' },
    { id: 7, name: '灼熱' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname, length: { maximum: 20 }
    validates :age, numericality: { only_integer: true }
    with_options numericality: { other_than: 1 } do
      validates :gender_id
      validates :sauna_history_id
    end
  end
  validates :self_introduction, length: { maximum: 1000 }
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i }

  def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
  end

  has_many :articles
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :image
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :sauna_history
end

app/models/water_bath.rb
class WaterBath < ActiveHash::Base
  self.data = [
    { id: 1, name: '--' },
    { id: 2, name: 'ぬるめ' },
    { id: 3, name: 'ややぬるい' },
    { id: 4, name: '平温' },
    { id: 5, name: '低温' },
    { id: 6, name: 'かなり低温' },
    { id: 7, name: '極寒' }
  ]

  include ActiveHash::Associations
  has_many :articles
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GetReadySauna</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all'%>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render "shared/header" %>
<div class='main'>

  <div class='title-contents'>
    <h1 class='about-title'>
      サウナとは
    </h1>
    <h1 class='about-title'>
      人生である！！
    </h1>
    <p class='service-explain2'>
      汗したたる灼熱の刻を、ただひたすら無心で過ごし
    </p>
    <p class='service-explain2'>
      冷気ほとばしる水風呂で、熱せられた体を瞬時に冷やす
    </p>
    <p class='service-explain2'>
      その後、我々は<span>圧倒的な多幸感(整い)</span>に包まれる
    </p>
    <p class='service-explain2'>
      人生、苦難や我慢の日々が多いです
    </p>
    <p class='service-explain2'>
      そんな日々を耐え抜き努力した者には
    </p>
    <p class='service-explain2'>
      幸せな瞬間が訪れることでしょう
    </p>
  </div>

  

  <div class='ad-contents'>
    <h2 class='ad-title2'>
      なぜ、サウナに入ると整うのか？
    </h2>
    <p class='ad-explain2'>
      サウナの高温で血流を増加させ、水風呂で血管を一気に収縮させる
    </p>
    <p class='ad-explain2'>
      これを<span>温冷交代浴</span>という
    <p class='ad-explain2'>
      この急速に行われる血管の収縮により
    </p>
    <p class='ad-explain2'>
      脳に酸素が大量に送られやすくなる
    </p>
    <p class='ad-explain2'>
      その瞬間、整うという感覚に襲われるといわれている
    </p>
  </div>

<%= render "shared/footer" %>

app/views/pages/image.html.erb
<%= render "shared/header" %>

  <%= image_tag "sauna_logo.jpg", class: "sample-img" %>
  <%= image_tag "sauna1.jpg", class: "sample-img" %>
  <%= image_tag "sauna4.jpg", class: "sample-img" %>
  <%= image_tag "sauna6.jpg", class: "sample-img" %>
  <%= image_tag "sauna9.jpg", class: "sample-img" %>
  <%= image_tag "sauna10.jpg", class: "sample-img" %>
  <%= image_tag "sauna11.png", class: "sample-img" %>
  <%= image_tag "sauna12.png", class: "sample-img" %>
  <%= image_tag "sauna16.png", class: "sample-img" %>
  <%= image_tag "sauna17.png", class: "sample-img" %>

  <h1 class='service-title'>
    ♨️ご自由にお使いください♨️
  </h1>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<%# 下部広告部分 %>
<div class='ad-footer-contents'>
  <p class='ad-footer-explain'>
    サウナに入ってより人生を豊かに
  </p>
  <h2 class='ad-footer-title'>
    みんなで整い合おう！
  </h2>
</div>
<%# /下部広告部分 %>

<div class='footer'>
  <div class='footer-contents'>
    <div class='furima-details'>
      <h2 class='footer-content-head'>Get Ready サウナ!!とは？</h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>サウナの魅力</h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
    <div class='furima-details'>
      <h2 class='footer-content-head'>サウナー同士でつながろう</h2>
      <ul>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
        <li><%= link_to '', "#", class: "footer-link" %></li>
      </ul>
    </div>
  </div>
  <%= link_to image_tag("sauna.png", class:"logo-white"), "/" %>
  <p>© Get Ready サウナ!!</p>
</div>

app/views/shared/_header.html.erb
<%# CSS・・・assets/stylesheets/shared/header.css %>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<header class='top-page-header'>
  <div class='search-bar-contents'>
    <%= link_to image_tag("sauna.png", class:"sauna-icon"), "/" %>
    <%= form_with(url: search_articles_path, local: true, method: :get, class: "search-form") do |f| %>
      <%= f.text_field :keyword, placeholder: "キーワードから探す", class: "input-box" %>
      <%= f.submit "♨検索♨️", class: "search-button" %>
    <% end %>
  </div>
  <div class='nav'>
    <ul class='lists-left'>
      <li><%= link_to 'サウナとは', page_path('about'), class: "category-list" %></li>
      <li><%= link_to 'サウナ画像', page_path('image'), class: "category-list" %></li>
    </ul>
    <ul class='lists-right'>
      <% if user_signed_in? %>
        <li><%= link_to current_user.nickname, user_path(current_user.id), class: "header-list" %></li>
        <li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %></li>
      <% else %>
        <li><%= link_to 'ログイン', new_user_session_path, class: "login" %></li>
        <li><%= link_to '新規登録', new_user_registration_path, class: "sign-up" %></li>
      <% end %>
    </ul>
  </div>
</header>

app/views/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/shared/_second-footer.html.erb
<div class='footer'>
  <%= link_to image_tag("sauna.png", class:"second-fotter-logo"), "/" %>
</div>

app/views/shared/_second-header.html.erb
<header class='second-header'>
  <%= link_to image_tag("sauna.png", class:"second-logo"), "/" %>
</header>